### ISSUE TITLE
make petalinux sysroot target .PHONY

### ISSUE THREAD

**Issue by muwyse-amd** [Xilinx/mlir-air#114]
Add `.PHONY: sysroot` to the petalinux directory Makefile, otherwise the `sysroot` target will always be up-to-date as the target name is the same as the SYSROOT directory name.

This target must execute before the further steps of the platform build occur.

https://github.com/Xilinx/mlir-air/blob/4b3a639f0d84285f07de280cc69b80d0101bee3d/platforms/xilinx_vck190_air/petalinux/Makefile#L33

**Comment by FredKellerman** [comment]
Thank you @muwyse-amd for the fix here!
