### ISSUE TITLE
PYNQ packages

### ISSUE THREAD

**Issue by FredKellerman** [Xilinx/mlir-air#150]
Hi,  In the Pynq .spec file there is a Pynq package called aienginesv2 being built.  Is that package public somewhere?

Thank you!

See contents of: https://github.com/Xilinx/mlir-air/blob/main/pynq/vck190_air/vck190_air.spec

**Comment by fifield** [comment]
It's building this library:
https://github.com/Xilinx/embeddedsw/tree/xlnx_rel_v2021.2/XilinxProcessorIPLib/drivers/aienginev2

**Comment by FredKellerman** [comment]
Thank you for the quick answer!  I see, so this isn't a traditional Pynq package.  I will pass along to @schelleg :-)

You wouldn't happen to know of a public port of PYNQ for the VCK190 would you?

This is an interesting work all in itself, sorry for the interruption!
