### ISSUE TITLE
[xilinx_vck5000_air] make error: "exceeds the maximum 16G DDR capacity" of AXI NOC IP

### ISSUE THREAD

**Issue by nqdtan** [Xilinx/mlir-air#166]
Hi,

I'm trying to build the AIR platform for VCK5000 with Vivado 2022.1. I'm hitting the following error when running `make all` under `mlir-air/platforms/xilinx_vck5000_air`

> ERROR: [IP_Flow 19-5481] Logical NOC instance '/axi_noc_0' has a total of '32G' DDR memory assigned, this exceeds the maximum '16G' DDR capacity for this IP. Please review your NOC DDR memory configuration.

I'm not sure what I'm missing. I'm using the VCK5000 v1.0 board files. Please find the attached log file for reference.

Thanks!

[vivado.log](https://github.com/Xilinx/mlir-air/files/10693053/vivado.log)

**Comment by jgmelber** [comment]
Fixed in #167
