### ISSUE TITLE
Channel Broadcast Examples

### ISSUE THREAD

**Issue by hunhoffe** [Xilinx/mlir-air#689]
As far as I can tell, there's not a good way for an AIR programmer to explicitly indicate they want a broadcast operation using channels.

I've attempted to write two examples that broadcast an input `a` to 3 workers. In `single_herd`, there is a single herd of `size=[1, 3]` whereas in `multi_herd` there are 3 herds each of `size=[1, 1]`. The workers then add a unique value to each element in the input image and output the new image to a unique per-worker output channel.

When I run the examples, only one worker receives the input `a`, where - if I was actually broadcasting - all 3 workers should have received the broadcasted input.

Where I could rewrite the examples and write out all the operations manually (and assume that the compiler will recognize that a broadcast should occur) there's not way (from the python) to verify that this would occur. And that would also make the python example code less concise/specific, so I don't think that's the best path forward. 

I don't think my example code as-is is what the final API for broadcast should look like. I think ideally there would be be an explicit argument to the ChannelPut operation to indicate that data is intended to be broadcast (maybe something like a replication factor, which has been discussed in other concepts?)

The examples are in this PR https://github.com/Xilinx/mlir-air/pull/688 and are part of the effort to write channel examples https://github.com/Xilinx/mlir-air/issues/648

**Comment by hunhoffe** [comment]
@erwei-xilinx @fifield @jgmelber I'd appreciate your inputs on this topic on what a broadcast operation should look like!

**Comment by erwei-xilinx** [comment]
If compiling from the `air.dma_memcpy_nd` level down, in air there are `-air-broadcast-detection` and `-air-specialize-dma-broadcast` which automatically infers broadcastable data movements, and lower to `broadcast_set` IntegerSet attributes explicitly representing the data broadcasting pattern.

On the other hand, if compiling from `air.channel.puts/gets` then in AIR there isn't a way to infer the data broadcast pattern for you; you would have to explicitly annotate on air.channel the broadcast pattern, for the downstream passes to pick up. Here is an IR that I captured from test/xrt/08 which shows how to annotate air.channel to represent broadcast.

https://gist.github.com/erwei-xilinx/5e23a6949e4d745842fc68af6217b479

**Comment by erwei-xilinx** [comment]
Looking at the input IR written using python binding, there are a couple of key annotations missing. (1) air.channel needs to be annotated with `broadcast_shape` attribute, to show the post-broadcast channel shape at destinations. (2) the destination channel.gets inside of air.herd needs to be a function of herd induction vars, to distinguish each specific broadcasted destination that a certain core in herd should receive from. (3) Affine.if else condition inside herd on broadcast destinations to specify which destination which core should get data from.

**Comment by hunhoffe** [comment]
I believe this issue is about resolved, and the examples are now working in the PR. I'm waiting for PR merge before closing this issue.

**Comment by hunhoffe** [comment]
Fix merged in
