### ISSUE TITLE
Does MLIR-AIR Support VCK190 Platform?

### ISSUE THREAD

**Issue by micropuma** [Xilinx/mlir-air#808]
Hi, i am new here. I am currently exploring the use of MLIR-AIR for FPGA development and was wondering if it supports the VCK190 platform (Xilinx ZCU102-based). Specifically, I am interested in understanding whether the MLIR-AIR project has been tested or integrated with the VCK190 FPGA platform, and if so, what steps are required to set it up or any specific configurations needed for the platform.
Additionally, are there any tutorials or documentation available that can guide me through the process of setting up and using MLIR-AIR on the VCK190 platform?

**Comment by fifield** [comment]
VCK190 is not supported by mlir-air. There is some related discussion here https://github.com/Xilinx/ROCm-air-platforms/issues/16
